language: python
sudo: required
services:
  - docker
env:
  - COMPOSE_FILE=docker-compose-dev.yml

before_install:
  - docker version
  - docker-compose --version


script:
  - docker-compose up -d
  - /bin/sh tests/01_urlcheck.sh
  - docker-compose down -v
